name: Docker Image CI

on:
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set Image tag
      run: |
        echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
    
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/kissmarcell132/azurewebapptest:$IMAGE_TAG --tag ghcr.io/kissmarcell132/azurewebapptest:latest 
        docker login ghcr.io -u kissmarcell132 -p ${{secrets.GHCR_TOKEN}}
        docker push ghcr.io/kissmarcell132/azurewebapptest:$IMAGE_TAG
        docker push ghcr.io/kissmarcell132/azurewebapptest:latest

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'teszt-13A-A'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8a15944d65ec45fbbd246544e4161ac7 }}
        images: 'ghcr.io/kissmarcell132/azurewebapptest:${{ env.IMAGE_TAG }}'
